# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from window_person import DataEntryWindow_1 as fail_1
class Dismissal_transfer(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("Form")
        self.resize(400, 300)
        self.comboBox = QtWidgets.QComboBox(self)
        self.comboBox.setGeometry((QtCore.QRect(70, 80, 261, 31)))
        self.comboBox.setObjectName("comboBox")

        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(100, 225, 170, 40))
        self.pushButton.setText('Сохронить')

        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(100, 40, 171, 41))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.dateEdit = QtWidgets.QDateEdit(self)
        self.dateEdit.setGeometry(QtCore.QRect(130, 180, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDisplayFormat("dd.MM.yyyy")
        self.dateEdit.setDate(QtCore.QDate.currentDate())

        self.radioButton = QtWidgets.QRadioButton(self)
        self.radioButton.setGeometry(QtCore.QRect(10, 170, 101, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 200, 101, 21))
        self.radioButton_2.setObjectName("radioButton_2")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.setComboBoxItems(self.fio_bring_out())
        self.pushButton.clicked.connect(self.save_changes)
    def fio_bring_out(self):
        fio = fail_1.list_Data(self)
        fio_out = []
        for record in fio:
            fio_out.append(record[0])
        return fio_out
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Фамилия Имя Отчество"))
        self.radioButton.setText(_translate("Form", "Увальнение"))
        self.radioButton_2.setText(_translate("Form", "Перевод"))
    def setComboBoxItems(self, items):
        self.comboBox.addItems(items)

    def save_changes(self):
        selected_employee = self.comboBox.currentText()
        selected_date = self.dateEdit.date().toString("dd.MM.yyyy")
        if self.radioButton.isChecked():
            self.dismiss_employee(selected_employee, selected_date)
        elif self.radioButton_2.isChecked():
            self.transfer_employee(selected_employee, selected_date)

    def dismiss_employee(self, employee, date):
        employees = fail_1.list_Data(self)
        updated_employees = [e for e in employees if e[0] != employee]
        self.write_employee_data(updated_employees)
        self.write_dismissal_record(employee, date)
        QtWidgets.QMessageBox.information(self, "Успех", f"{employee} уволен.")

    def transfer_employee(self, employee, date):
        new_position, ok = QtWidgets.QInputDialog.getText(self, "Перевод", "Введите новую должность:")
        if ok:
            employees = fail_1.list_Data(self)
            for e in employees:
                if e[0] == employee:
                    e[1] = new_position
            self.write_employee_data(employees)
            QtWidgets.QMessageBox.information(self, "Успех", f"{employee} переведен на должность {new_position}.")

    def write_employee_data(self, data):
        with open("employee_data.txt", "w") as file:
            for record in data:
                file.write(", ".join(record) + "\n")

    def write_dismissal_record(self, employee, date):
        with open("dismissal_transfer.txt", "a") as file:
            file.write(f"{employee}, уволен: {date}\n")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Dismissal_transfer()
    ui.show()
    sys.exit(app.exec_())
