# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from window_person import DataEntryWindow_1 as fail_1
class Dismissal_transfer(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("Form")
        self.resize(400, 300)
        self.comboBox = QtWidgets.QComboBox(self)
        self.comboBox.setGeometry((QtCore.QRect(70, 80, 261, 31)))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_1 = QtWidgets.QComboBox(self)
        self.comboBox_1.setGeometry(QtCore.QRect(70, 200, 261, 31))
        self.comboBox_1.setObjectName("comboBox")
        self.comboBox_1.addItems(["Уволен", "Cмена A", "Cмена B", "Cмена C", "Cмена D","Пятидневка"])

        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(150, 240, 101, 31))
        self.pushButton.setObjectName("pushButton")

        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(100, 40, 171, 41))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 41, 31))
        self.label_2.setToolTip("")
        self.label_2.setToolTipDuration(-1)
        self.label_2.setLineWidth(0)
        self.label_2.setMidLineWidth(0)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setIndent(1)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")

        self.dateEdit = QtWidgets.QDateEdit(self)
        self.dateEdit.setGeometry(QtCore.QRect(150, 150, 121, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDisplayFormat("dd.MM.yyyy")
        self.dateEdit.setDate(QtCore.QDate.currentDate())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.setComboBoxItems(self.fio_bring_out())
        self.pushButton.clicked.connect(self.save_changes)
    def fio_bring_out(self):
        fio = fail_1.list_Data(self)
        fio_out = []
        for record in fio:
            fio_out.append(record[0])
        return fio_out
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Фамилия Имя Отчество"))
        self.label_2.setText(_translate("Form", "Дата"))
        self.pushButton.setText(_translate("Form", "Сохранить"))
    def setComboBoxItems(self, items):
        self.comboBox.addItems(items)

    def save_changes(self):
        selected_employee = self.comboBox.currentText()
        selected_date = self.dateEdit.date().toString("dd.MM.yyyy")
        if self.radioButton.isChecked():
            self.dismiss_employee(selected_employee, selected_date)
        elif self.radioButton_2.isChecked():
            self.transfer_employee(selected_employee, selected_date)

    def dismiss_employee(self, employee, date):
        employees = fail_1.list_Data(self)
        updated_employees = [e for e in employees if e[0] != employee]
        self.write_employee_data(updated_employees)
        self.write_dismissal_record(employee, date)
        QtWidgets.QMessageBox.information(self, "Успех", f"{employee} уволен.")

    def transfer_employee(self, employee, date):
        new_position, ok = QtWidgets.QInputDialog.getText(self, "Перевод", "Введите новую должность:")
        if ok:
            employees = fail_1.list_Data(self)
            for e in employees:
                if e[0] == employee:
                    e[1] = new_position
            self.write_employee_data(employees)
            QtWidgets.QMessageBox.information(self, "Успех", f"{employee} переведен на должность {new_position}.")




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Dismissal_transfer()
    ui.show()
    sys.exit(app.exec_())
